Quiz app
Shweta2024/JavaScript-Projects pull request #125
Opened 2022-12-20 16:04 UTC by murph1234

## Related Issue
#114 
I wanted to make a few changes in the css as the page is not looking attractive and appealing as it should be with respect to a quiz game. I would like to make the texts on the page a bit more organized and also make some changes on the background image.
 

### Describe Changes
As I have described above I have made changes with the website layout by adding Bootstrap. This enhanced the font style and the overall look of the website. I have also made the buttons rounded by changing its border radius. I have completely modified the CSS of chemistry, computer and maths page by maintaing the texts as it should be( in center).Moreover when the result was showing a thick border of red , yellow and green was coming which was looking a bit odd.I changed it and rather made the text show the respective colors which is looking better.This change I made in the JS file of the respective subjects.

##Screenshots
![image](https://user-images.githubusercontent.com/98601458/208711439-11d844f3-5abd-41d5-9d4c-ac0c94020052.png)
 
The other pages are looking the same way!

### Checklist

- [ x] ✅ My code follows the code style of this project.
- [x ] 🚩 All new and existing tests passed.
- [x ] 🌟 I have starred the repo
- [x ] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-12-20 16:06 UTC, utkarsh006 commented
@murph1234 Tickmark checkboxes like this[x]

2022-12-20 16:07 UTC, murph1234 commented
@utkarsh006 done!!

2022-12-21 07:55 UTC, Shweta2024 commented
> @utkarsh006 done!!

@murph1234 
tick mark the checkboxes of "What types of changes does your code introduce?" like [x] this

2022-12-21 08:25 UTC, murph1234 commented
@Shweta2024 done!!

2022-12-21 10:33 UTC, utkarsh006 commented
@murph1234 Add README file.

2022-12-22 17:30 UTC, utkarsh006 commented
@murph1234 Answer my review above.

2022-12-22 17:36 UTC, murph1234 commented
@utkarsh006 I am not able to find the reviews

2022-12-22 17:39 UTC, utkarsh006 commented
## Here it is!
![Screenshot (303)](https://user-images.githubusercontent.com/94545831/209193982-60a37265-6f6a-421e-9b36-682b665cbcac.png)

2022-12-22 17:46 UTC, murph1234 commented
@utkarsh006 previously it was showing a block of color (red,yellow and green) respectively which was looking a bit odd with respect to the background image but now only the text is getting colored which is looking better

2022-12-23 17:44 UTC, utkarsh006 commented
@murph1234 Upload video of your project in README and add comments to the code.

2022-12-23 17:58 UTC, murph1234 commented on Quiz-App/js/chemistry.js
> +    document.getElementById("result").style.color = "red";
previously it was showing a block of color (red,yellow and green) respectively which was looking a bit odd with respect to the background image but now only the text is getting colored which is looking better

2022-12-23 18:39 UTC, murph1234 commented
@utkarsh006 done!!

2022-12-24 11:09 UTC, utkarsh006 commented
@murph1234 Add comments to the JS code

2022-12-24 11:17 UTC, murph1234 commented
I had to do it in all the JS codes i have already done it in chemistry

2022-12-24 11:18 UTC, murph1234 commented
@utkarsh006

2022-12-24 11:42 UTC, utkarsh006 commented
@murph1234 I think rather than arguments you must follow guidelines. And write one message at a time for replying.

2022-12-24 11:53 UTC, murph1234 commented
@utkarsh006 done

2022-12-24 11:53 UTC, murph1234 commented
@utkarsh006 done

2022-12-28 09:05 UTC, Shweta2024 requested changes
resolve merge conflicts

2022-12-28 09:37 UTC, murph1234 commented
@Shweta2024 how to do it?

2022-12-30 14:58 UTC, utkarsh006 commented
@murph1234 Close the PR and raise another new PR following all the guidelines.

2022-12-30 14:58 UTC, closed without merging